// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// IMPORTANT: This file is generated by the FlutterFire CLI.
// It contains the Firebase project configuration for different platforms.
// Do not modify this file manually. Any changes will be overwritten.
// To reconfigure your project, run `flutterfire configure` in your terminal.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This class provides platform-specific Firebase configurations.
/// The `currentPlatform` getter automatically determines the correct options
/// based on the runtime environment (web, Android, iOS, etc.).
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- Platform-Specific Firebase Configurations ---

  // Configuration for the Web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your actual API key if needed
    appId: '1:115277521404:web:d9eaf0cc5021986b2a1279',
    messagingSenderId: '115277521404',
    projectId: 'blossom-app-be0e5',
    authDomain: 'blossom-app-be0e5.firebaseapp.com',
    storageBucket: 'blossom-app-be0e5.firebasestorage.app',
    measurementId: 'G-D7C6FTM8Z6',
    databaseURL:
        'https://blossom-app-be0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  // Configuration for the Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your actual API key if needed
    appId: '1:115277521404:android:0cea7338073ac97a2a1279',
    messagingSenderId: '115277521404',
    projectId: 'blossom-app-be0e5',
    storageBucket: 'blossom-app-be0e5.firebasestorage.app',
    databaseURL:
        'https://blossom-app-be0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  // Configuration for the iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your actual API key if needed
    appId: '1:115277521404:ios:39ef15c286257f2e2a1279',
    messagingSenderId: '115277521404',
    projectId: 'blossom-app-be0e5',
    storageBucket: 'blossom-app-be0e5.firebasestorage.app',
    iosBundleId: 'com.example.blossomApp',
    databaseURL:
        'https://blossom-app-be0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  // Configuration for the macOS platform.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your actual API key if needed
    appId: '1:115277521404:ios:39ef15c286257f2e2a1279',
    messagingSenderId: '115277521404',
    projectId: 'blossom-app-be0e5',
    storageBucket: 'blossom-app-be0e5.firebasestorage.app',
    iosBundleId: 'com.example.blossomApp',
    databaseURL:
        'https://blossom-app-be0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  // Configuration for the Windows platform.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your actual API key if needed
    appId: '1:115277521404:web:54261fa5278e06102a1279',
    messagingSenderId: '115277521404',
    projectId: 'blossom-app-be0e5',
    authDomain: 'blossom-app-be0e5.firebaseapp.com',
    storageBucket: 'blossom-app-be0e5.firebasestorage.app',
    measurementId: 'G-JVX2N05KBN',
    databaseURL:
        'https://blossom-app-be0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
